name: Build .NET project

on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["10.0.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version}}
      
      - name: Restore dependencies
        run: dotnet restore ExternalLoginAnd2FA/ExternalLoginAnd2FA.sln

      - name: Clean previous builds
        run: dotnet clean ExternalLoginAnd2FA/ExternalLoginAnd2FA.sln --configuration release

      - name: Build project
        run: dotnet build ExternalLoginAnd2FA/ExternalLoginAnd2FA.sln --configuration release --no-restore

      