name: Build .NET project

on:
  push:
    branches: 
      - 'main'
    tags:
      - "*"
  pull_request:
    branches: 
      - 'main'
    types: [opened,synchronize,reopened]

  release:
    types: [published]

jobs:
  build-unitTest-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["10.0.x"]

    env:
      SOLUTION_PATH: ExternalLoginAnd2FA/ExternalLoginAnd2FA.sln
      TEST_RESULTS_DIR: ExternalLoginAnd2FA/ExternalLoginAnd2FA.Web.Tests
      DOCKER_SERVICE: web
      DOCKER_IMAGE_NAME: externalloginand2fa
      DOCKER_COMPOSE_FILE: ExternalLoginAnd2FA.Web/docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version}}
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Clean previous builds
        run: dotnet clean ${{ env.SOLUTION_PATH }} --configuration release

      - name: Build project
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration release --no-restore

      - name: Run unit tests
        run: |
          dotnet test "${{ env.SOLUTION_PATH }}" \
            --configuration Release \
            --logger "trx;LogFileName=TestResults-${{ github.ref_name }}.trx" \
            --results-directory "${{ env.TEST_RESULTS_DIR }}"

      - name: Upload unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-tests-${{ github.run_number }}
          path: ${{ env.TEST_RESULTS_DIR }}

      - name: Setup Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Update Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install --only-upgrage docker.io

      - name: Log In to DockerHub
        if: github.event_name == "push" && startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: Configure Docker for reduced concurrent uploads
        if: github.event_name == "push" && startsWith(github.ref, 'refs/tags/')
        run: |
          echo '{"max-concurrent-uploads": 1}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build Web app Docker image
        run: |
          docker compose -f "${{ env.DOCKER_COMPOSE_FILE }}" build "${{ env.DOCKER_SERVICE}}"

      - name: Push Web app Docker image to DockerHub
        if: github.event_name == "push" && startsWith(github.ref, 'refs/tags/')
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "Pushing to DockerHub with tag: $TAG_NAME"
          for i in {1..3}; do
            docker tag ${{env.DOCKER_IMAGE_NAME}}:latest ${{ secrets.DOCKERHUB_REPOSITORY}}:$TAG_NAME
            docker push ${{ secrets.DOCKERHUB_REPOSITORY}}:$TAG_NAME && break || echo "Retrying docker push ($i)...."
            sleep 10
          done
          for i in {1..3}; do
            docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:latest && break || echo "Retrying docker push ($i)...."
            sleep 10
          done






      